apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: amicitia/lumi-backend:56
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"

          env:
            # [Spring Profile 설정]
            - name: SPRING_PROFILES_ACTIVE
              value: dev

            # [DB 설정]
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mariadb://mariadb:3306/2nd_project
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: SPRING_DATASOURCE_PASSWORD

            # [Redis 설정]
            - name: SPRING_DATA_REDIS_HOST
              value: redis
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"

            # [JWT 설정]
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: JWT_SECRET
            - name: JWT_ACCESS_EXPIRATION
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: JWT_ACCESS_EXPIRATION
            - name: JWT_REFRESH_EXPIRATION
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: JWT_REFRESH_EXPIRATION

            # [메일 설정]
            - name: SPRING_MAIL_HOST
              value: smtp.gmail.com
            - name: SPRING_MAIL_PORT
              value: "587"
            - name: SPRING_MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: SPRING_MAIL_USERNAME
            - name: SPRING_MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: SPRING_MAIL_PASSWORD
            - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH
              value: "true"
            - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE
              value: "true"

            # [타임존 설정]
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: TIME_ZONE

            - name: FILE_UPLOAD_DIR
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: FILE_UPLOAD_DIR

          volumeMounts:
            - name: uploads
              mountPath: /spring-boot/uploads
            - name: logs
              mountPath: /spring-boot/logs

          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 60
            timeoutSeconds: 5

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 10
            failureThreshold: 10
            timeoutSeconds: 5

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 180
            periodSeconds: 20
            failureThreshold: 10
            timeoutSeconds: 5


      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: backend-uploads-pvc
        - name: logs
          emptyDir: {}
