apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:11.8.2
          ports:
            - containerPort: 3306
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: ROOT_PASSWORD
            - name: MARIADB_DATABASE
              value: "2nd_project"
            - name: MARIADB_USER
              value: "beyond"
            - name: MARIADB_PASSWORD
              value: "beyond"
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: TIME_ZONE
          volumeMounts:
            - name: mariadb-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mariadb-data
          persistentVolumeClaim:
            claimName: mariadb-pvc
